version: "3"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: exdti_web_server
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: python main.py