version: "3"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: exdti_web_server
    volumes:
      - .:/app
    ports:
      - 8000:8001
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8001 --log-level debug